modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"

[[mods]]
modId = "create_e2e"
version = "1.0.0"
displayName = "Create end-to-end tests"
description = '''Create's client gametests, re-expressed against a real dedicated server and a real client.'''

[[dependencies.create_e2e]]
modId = "create"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_e2e]]
modId = "mcdriver"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
